//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dang_ky_mon_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGDIEM
    {
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> DiemKiemTra { get; set; }
        public Nullable<double> DiemGiuaKy { get; set; }
        public Nullable<double> DiemCuoiKy { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
