//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dang_ky_mon_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDAOTAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTDAOTAO()
        {
            this.MONHOC_DAOTAO = new HashSet<MONHOC_DAOTAO>();
            this.LOPs = new HashSet<LOP>();
        }
    
        public string MaCTDT { get; set; }
        public string TenCTDT { get; set; }
        public string HinhThucDT { get; set; }
        public string NgonNguDT { get; set; }
        public string TrinhDoDaoTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONHOC_DAOTAO> MONHOC_DAOTAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
