//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dang_ky_mon_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKY_MONHOC
    {
        public string MaSV { get; set; }
        public string MaLopHoc { get; set; }
        public string KetQua { get; set; }
    
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
