//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dang_ky_mon_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPHOC()
        {
            this.DANGKY_MONHOC = new HashSet<DANGKY_MONHOC>();
        }
    
        public string MaLopHoc { get; set; }
        public string MaMHDT { get; set; }
        public string MaGV { get; set; }
        public Nullable<int> GioiHan { get; set; }
        public string TenPhong { get; set; }
        public string Thu { get; set; }
        public Nullable<int> TietBatDau { get; set; }
        public Nullable<int> TietKetThuc { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string HocKy { get; set; }
        public Nullable<int> Nam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKY_MONHOC> DANGKY_MONHOC { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual MONHOC_DAOTAO MONHOC_DAOTAO { get; set; }
    }
}
