//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dang_ky_mon_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONHOC_DAOTAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONHOC_DAOTAO()
        {
            this.LOPHOCs = new HashSet<LOPHOC>();
        }
    
        public string MaMHDT { get; set; }
        public string MaMH { get; set; }
        public string MaCTDT { get; set; }
        public string MaNganh { get; set; }
    
        public virtual CTDAOTAO CTDAOTAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOPHOC> LOPHOCs { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual NGANH NGANH { get; set; }
    }
}
