//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dang_ky_mon_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY
    {
        public string MaQL { get; set; }
        public string TenNQL { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
